name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check PHP
        run: php -v

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
      
      - name Create environment file
        run: cp .env.example .env

      - name: Generate application key
        run: php artisan key:generate

      - name: Run Tests
        run: php artisan test
        
      


      